name: DB Liquibase CI

on:
  pull_request:
    branches: [ main, master, develop ]
  push:
    branches: [ main, master, develop ]

jobs:
  liquibase-validate-and-update:
    name: Validar y compilar cambios Liquibase
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: cafeteria_db
          POSTGRES_USER: cafeteria_user
          POSTGRES_PASSWORD: cafeteria_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U cafeteria_user -d cafeteria_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Descargar código
        uses: actions/checkout@v4
      - name: Ejecutar validate
        uses: liquibase-github-actions/validate@v4.31.0
        with:
          changelogFile: liquibase/changelog-master.xml
          url: jdbc:postgresql://localhost:5432/cafeteria_db
          username: cafeteria_user
          password: cafeteria_pass
      - name: Probar update contra PostgreSQL temporal
        uses: liquibase-github-actions/update@v4.31.0
        with:
          changelogFile: liquibase/changelog-master.xml
          url: jdbc:postgresql://localhost:5432/cafeteria_db
          username: cafeteria_user
          password: cafeteria_pass

  verify-sql-files:
    name: Verificar estructura y archivos SQL
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4
      - name: Revisar carpetas obligatorias
        run: |
          test -d 01_tables
          test -d 09_inserts
          test -d 11_rollbacks
          test -f liquibase/changelog-master.xml
      - name: Revisar que existan archivos SQL principales
        run: |
          test -s 01_tables/001_create_tables.sql
          test -s 09_inserts/001_seed_data.sql
          test -s 11_rollbacks/002_drop_tables.sql
